interface ICountriesData {
    country: string;
    key: string;
    flag: string;
  }

export const countriesData: ICountriesData[] = [
    { country: "Afghanistan", key: "af", flag: "af" },
    { country: "Albania", key: "al", flag: "al" },
    { country: "Algeria", key: "dz", flag: "dz" },
    { country: "Andorra", key: "ad", flag: "ad" },
    { country: "Angola", key: "ao", flag: "ao" },
    { country: "Antigua and Barbuda", key: "ag", flag: "ag" },
    { country: "Argentina", key: "ar", flag: "ar" },
    { country: "Armenia", key: "am", flag: "am" },
    { country: "Australia", key: "au", flag: "au" },
    { country: "Austria", key: "at", flag: "at" },
    { country: "Azerbaijan", key: "az", flag: "az" },
    { country: "Bahamas", key: "bs", flag: "bs" },
    { country: "Bahrain", key: "bh", flag: "bh" },
    { country: "Bangladesh", key: "bd", flag: "bd" },
    { country: "Barbados", key: "bb", flag: "bb" },
    { country: "Belarus", key: "by", flag: "by" },
    { country: "Belgium", key: "be", flag: "be" },
    { country: "Belize", key: "bz", flag: "bz" },
    { country: "Benin", key: "bj", flag: "bj" },
    { country: "Bhutan", key: "bt", flag: "bt" },
    { country: "Bolivia", key: "bo", flag: "bo" },
    { country: "Bosnia and Herzegovina", key: "ba", flag: "ba" },
    { country: "Botswana", key: "bw", flag: "bw" },
    { country: "Brazil", key: "br", flag: "br" },
    { country: "Brunei", key: "bn", flag: "bn" },
    { country: "Bulgaria", key: "bg", flag: "bg" },
    { country: "Burkina Faso", key: "bf", flag: "bf" },
    { country: "Burundi", key: "bi", flag: "bi" },
    { country: "Cambodia", key: "kh", flag: "kh" },
    { country: "Cameroon", key: "cm", flag: "cm" },
    { country: "Canada", key: "ca", flag: "ca" },
    { country: "Cape Verde", key: "cv", flag: "cv" },
    { country: "Central African Republic", key: "cf", flag: "cf" },
    { country: "Chad", key: "td", flag: "td" },
    { country: "Chile", key: "cl", flag: "cl" },
    { country: "China", key: "cn", flag: "cn" },
    { country: "Colombia", key: "co", flag: "co" },
    { country: "Comoros", key: "km", flag: "km" },
    { country: "Congo", key: "cg", flag: "cg" },
    { country: "Costa Rica", key: "cr", flag: "cr" },
    { country: "Croatia", key: "hr", flag: "hr" },
    { country: "Cuba", key: "cu", flag: "cu" },
    { country: "Cyprus", key: "cy", flag: "cy" },
    { country: "Czech Republic", key: "cz", flag: "cz" },
    { country: "Democratic Republic of the Congo", key: "cd", flag: "cd" },
    { country: "Denmark", key: "dk", flag: "dk" },
    { country: "Djibouti", key: "dj", flag: "dj" },
    { country: "Dominica", key: "dm", flag: "dm" },
    { country: "Dominican Republic", key: "do", flag: "do" },
    { country: "East Timor", key: "tl", flag: "tl" },
    { country: "Ecuador", key: "ec", flag: "ec" },
    { country: "Egypt", key: "eg", flag: "eg" },
    { country: "El Salvador", key: "sv", flag: "sv" },
    { country: "Equatorial Guinea", key: "gq", flag: "gq" },
    { country: "Eritrea", key: "er", flag: "er" },
    { country: "Estonia", key: "ee", flag: "ee" },
    { country: "Ethiopia", key: "et", flag: "et" },
    { country: "Fiji", key: "fj", flag: "fj" },
    { country: "Finland", key: "fi", flag: "fi" },
    { country: "France", key: "fr", flag: "fr" },
    { country: "Gabon", key: "ga", flag: "ga" },
    { country: "Gambia", key: "gm", flag: "gm" },
    { country: "Georgia", key: "ge", flag: "ge" },
    { country: "Germany", key: "de", flag: "de" },
    { country: "Ghana", key: "gh", flag: "gh" },
    { country: "Greece", key: "gr", flag: "gr" },
    { country: "Grenada", key: "gd", flag: "gd" },
    { country: "Guatemala", key: "gt", flag: "gt" },
    { country: "Guinea", key: "gn", flag: "gn" },
    { country: "Guinea-Bissau", key: "gw", flag: "gw" },
    { country: "Guyana", key: "gy", flag: "gy" },
    { country: "Haiti", key: "ht", flag: "ht" },
    { country: "Honduras", key: "hn", flag: "hn" },
    { country: "Hungary", key: "hu", flag: "hu" },
    { country: "Iceland", key: "is", flag: "is" },
    { country: "India", key: "in", flag: "in" },
    { country: "Indonesia", key: "id", flag: "id" },
    { country: "Iran", key: "ir", flag: "ir" },
    { country: "Iraq", key: "iq", flag: "iq" },
    { country: "Ireland", key: "ie", flag: "ie" },
    { country: "Israel", key: "il", flag: "il" },
    { country: "Italy", key: "it", flag: "it" },
    { country: "Ivory Coast", key: "ci", flag: "ci" },
    { country: "Jamaica", key: "jm", flag: "jm" },
    { country: "Japan", key: "jp", flag: "jp" },
    { country: "Jordan", key: "jo", flag: "jo" },
    { country: "Kazakhstan", key: "kz", flag: "kz" },
    { country: "Kenya", key: "ke", flag: "ke" },
    { country: "Kiribati", key: "ki", flag: "ki" },
    { country: "Kuwait", key: "kw", flag: "kw" },
    { country: "Kyrgyzstan", key: "kg", flag: "kg" },
    { country: "Laos", key: "la", flag: "la" },
    { country: "Latvia", key: "lv", flag: "lv" },
    { country: "Lebanon", key: "lb", flag: "lb" },
    { country: "Lesotho", key: "ls", flag: "ls" },
    { country: "Liberia", key: "lr", flag: "lr" },
    { country: "Libya", key: "ly", flag: "ly" },
    { country: "Liechtenstein", key: "li", flag: "li" },
    { country: "Lithuania", key: "lt", flag: "lt" },
    { country: "Luxembourg", key: "lu", flag: "lu" },
    { country: "Madagascar", key: "mg", flag: "mg" },
    { country: "Malawi", key: "mw", flag: "mw" },
    { country: "Malaysia", key: "my", flag: "my" },
    { country: "Maldives", key: "mv", flag: "mv" },
    { country: "Mali", key: "ml", flag: "ml" },
    { country: "Malta", key: "mt", flag: "mt" },
    { country: "Marshall Islands", key: "mh", flag: "mh" },
    { country: "Mauritania", key: "mr", flag: "mr" },
    { country: "Mauritius", key: "mu", flag: "mu" },
    { country: "Mexico", key: "mx", flag: "mx" },
    { country: "Micronesia", key: "fm", flag: "fm" },
    { country: "Moldova", key: "md", flag: "md" },
    { country: "Monaco", key: "mc", flag: "mc" },
    { country: "Mongolia", key: "mn", flag: "mn" },
    { country: "Montenegro", key: "me", flag: "me" },
    { country: "Morocco", key: "ma", flag: "ma" },
    { country: "Mozambique", key: "mz", flag: "mz" },
    { country: "Myanmar", key: "mm", flag: "mm" },
    { country: "Namibia", key: "na", flag: "na" },
    { country: "Nauru", key: "nr", flag: "nr" },
    { country: "Nepal", key: "np", flag: "np" },
    { country: "Netherlands", key: "nl", flag: "nl" },
    { country: "New Zealand", key: "nz", flag: "nz" },
    { country: "Nicaragua", key: "ni", flag: "ni" },
    { country: "Niger", key: "ne", flag: "ne" },
    { country: "Nigeria", key: "ng", flag: "ng" },
    { country: "North Korea", key: "kp", flag: "kp" },
    { country: "North Macedonia", key: "mk", flag: "mk" },
    { country: "Norway", key: "no", flag: "no" },
    { country: "Oman", key: "om", flag: "om" },
    { country: "Pakistan", key: "pk", flag: "pk" },
    { country: "Palau", key: "pw", flag: "pw" },
    { country: "Palestine", key: "ps", flag: "ps" },
    { country: "Panama", key: "pa", flag: "pa" },
    { country: "Papua New Guinea", key: "pg", flag: "pg" },
    { country: "Paraguay", key: "py", flag: "py" },
    { country: "Peru", key: "pe", flag: "pe" },
    { country: "Philippines", key: "ph", flag: "ph" },
    { country: "Poland", key: "pl", flag: "pl" },
    { country: "Portugal", key: "pt", flag: "pt" },
    { country: "Qatar", key: "qa", flag: "qa" },
    { country: "Romania", key: "ro", flag: "ro" },
    { country: "Russia", key: "ru", flag: "ru" },
    { country: "Rwanda", key: "rw", flag: "rw" },
    { country: "Saint Kitts and Nevis", key: "kn", flag: "kn" },
    { country: "Saint Lucia", key: "lc", flag: "lc" },
    { country: "Saint Vincent and the Grenadines", key: "vc", flag: "vc" },
    { country: "Samoa", key: "ws", flag: "ws" },
    { country: "San Marino", key: "sm", flag: "sm" },
    { country: "Sao Tome and Principe", key: "st", flag: "st" },
    { country: "Saudi Arabia", key: "sa", flag: "sa" },
    { country: "Senegal", key: "sn", flag: "sn" },
    { country: "Serbia", key: "rs", flag: "rs" },
    { country: "Seychelles", key: "sc", flag: "sc" },
    { country: "Sierra Leone", key: "sl", flag: "sl" },
    { country: "Singapore", key: "sg", flag: "sg" },
    { country: "Slovakia", key: "sk", flag: "sk" },
    { country: "Slovenia", key: "si", flag: "si" },
    { country: "Solomon Islands", key: "sb", flag: "sb" },
    { country: "Somalia", key: "so", flag: "so" },
    { country: "South Africa", key: "za", flag: "za" },
    { country: "South Korea", key: "kr", flag: "kr" },
    { country: "South Sudan", key: "ss", flag: "ss" },
    { country: "Spain", key: "es", flag: "es" },
    { country: "Sri Lanka", key: "lk", flag: "lk" },
    { country: "Sudan", key: "sd", flag: "sd" },
    { country: "Suriname", key: "sr", flag: "sr" },
    { country: "Sweden", key: "se", flag: "se" },
    { country: "Switzerland", key: "ch", flag: "ch" },
    { country: "Syria", key: "sy", flag: "sy" },
    { country: "Taiwan", key: "tw", flag: "tw" },
    { country: "Tajikistan", key: "tj", flag: "tj" },
    { country: "Tanzania", key: "tz", flag: "tz" },
    { country: "Thailand", key: "th", flag: "th" },
    { country: "Togo", key: "tg", flag: "tg" },
    { country: "Tonga", key: "to", flag: "to" },
    { country: "Trinidad and Tobago", key: "tt", flag: "tt" },
    { country: "Tunisia", key: "tn", flag: "tn" },
    { country: "Turkey", key: "tr", flag: "tr" },
    { country: "Turkmenistan", key: "tm", flag: "tm" },
    { country: "Tuvalu", key: "tv", flag: "tv" },
    { country: "Uganda", key: "ug", flag: "ug" },
    { country: "Ukraine", key: "ua", flag: "ua" },
    { country: "United Arab Emirates", key: "ae", flag: "ae" },
    { country: "United Kingdom", key: "gb", flag: "gb" },
    { country: "United States", key: "us", flag: "us" },
    { country: "Uruguay", key: "uy", flag: "uy" },
    { country: "Uzbekistan", key: "uz", flag: "uz" },
    { country: "Vanuatu", key: "vu", flag: "vu" },
    { country: "Vatican City", key: "va", flag: "va" },
    { country: "Venezuela", key: "ve", flag: "ve" },
  { country: "Vietnam", key: "vn", flag: "vn" },
  { country: "Yemen", key: "ye", flag: "ye" },
  { country: "Zambia", key: "zm", flag: "zm" },
  { country: "Zimbabwe", key: "zw", flag: "zw" }
];

export const selectedCountryOption = (country: string) =>
    countriesData.find((option) => option.country === country);